using System.ComponentModel.DataAnnotations;

namespace BluestaqNotesApp.DTOs;

public class CreateNoteRequest
{
    //user provides only Content; Id and CreatedAt are generated by the system
    [Required]
    [MinLength(1)]
    public string Content { get; set; } = string.Empty;
}